version: '3.8'

services:
    dev:
        container_name: events_dev_api
        image: events_dev_api:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3001:3001
        networks:
            - dev-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    dev-network: